INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (1, 'James', 'Bond');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (2, 'James', 'Bond');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (3, 'James', 'Bond');